version: 0.2

phases :
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hasicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip"
      - "unzip terraform_1.0.5_linux_amd64.zip"
      - "mv terraform /user/local/bin"
    build:
      commands:
        - terraform $TF_COMMAND -auto-approve

    post_build:
      commands:
        - echo terraform $TF_COMMAND completed on  `date`